apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      containers:
      - env:
        - name: TRAFFIC
          value: '400'
        - name: FRONTEND_ADDR
          value: frontend:80
        - name: USERS
          value: '10'
        image: loadgenerator
        #image: gcr.io/liquid-champion-244004/loadgenerator:v1
        #imagePullPolicy: Always
        name: main
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 300m
            memory: 256Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
